config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profile, only: :index

  resources :instruments

  resources :users, only: [ :show ] do
    resources :instruments, only: [ :index ]
  end

  resources :orders, only: [ :index, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :orders
  validates :name, presence: true
  validates :inst_type, presence: true
  validates :price, presence: true

  # include PgSearch::Model
  # multisearchable against: [:user]
  has_many_attached :photo
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :instruments, dependent: :destroy
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_instrument, only: [ :show, :edit, :update, :destroy]
  def index
    @instruments = policy_scope(Instrument)
  end

  def show
  end

  def new
    @instrument = Instrument.new
    authorize @instrument
  end

  def edit
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user

    authorize @instrument
    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render :new
    end
  end

# Modificar o def update inserindo um 'if' como o do create
  def update
    @instrument.update(instrument_params)

    redirect_to instrument_path(@instrument.id)
  end

  def destroy
    @instrument.delete

    redirect_to instruments_path
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
    authorize @instrument
  end

  def instrument_params
    params.require(:instrument).permit(:name, :inst_type, :price, :description, photo: [])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_after_action :verify_authorized

  def index
    @order = current_user.orders
  end

  def create
    @order = Order.new
    @order.date = DateTime.now

    @order.instrument = Instrument.find(params[:instrument_id])
    @order.user = current_user
    @order.save
    # Change the owner of the instrument changes.
    purchased_instrument =  Instrument.find(params[:instrument_id])
    purchased_instrument.user_id = current_user.id
    purchased_instrument.purchased = true
    purchased_instrument.save
    redirect_to profile_index_path
  end

  def edit
    @order = Order.task.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
  end

  def destroy
    @order = Order.find(params[:id])
    @order.update(order_params)
  end

  private

  def order_params
      params.require(:order).permit(:instrument, :user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    # @instruments = current_user.instruments
    @instruments = if current_user.admin
      policy_scope(Instrument)
    else
      policy_scope(Instrument).where(user: current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instruments/edit.html.erb
<%= simple_form_for @instrument do |f| %>
  <%= f.input :name, label: 'Instrumento' %>
  <%= f.input :inst_type, label: 'Tipo de Instrumento' %>
  <%= f.input :price, label: 'Preço' %>
  <%= f.submit 'Atualizar Anúncio', class: 'btn btn-primary' %>
<% end %>

app/views/instruments/index.html.erb
<%= link_to new_instrument_path do %>
  <div class="btn-index">
    <span><%= "Novo anúncio" %></span>
  </div>
<% end %>
<% @instruments.each do |instrument| %>
  <%= link_to instrument_path(instrument) do %>
    <div class="card-product">
      <% if instrument.photo.any? %>
        <div class="card-index mt-10" style="background-image: linear-gradient(rgba(255, 164, 27, 0.3), rgba(255, 164, 27, 0.3)), url('<%= cl_image_path instrument.photo.last.key %>'); width:360px; height: 350px;" >
        <% else %>
        <div class="card-index mt-10" style='background-image: linear-gradient(rgba(255, 164, 27, 0.3), rgba(255, 164, 27, 0.3)), url(https://i.picsum.photos/id/145/4288/2848.jpg); width:360px; height: 350px;' >
        <% end %>
        </div>
      <div class="card-product-infos">
        <h4><%= instrument.name %></h4>
        <p><%=  instrument.description %></p>
        <p> <%= number_to_currency instrument.price %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/instruments/new.html.erb
<h1 class='m-3 form'>Novo Instrumento</h1>

<div class='m-3 form'>
  <%= simple_form_for(@instrument) do |f| %>


    <%= f.input :name, label: "Instrumento" %>
    <%= f.input :inst_type, label: "Tipo de instrumento" %>
    <%= f.input :description, label: "Descrição do Anuncio" %>
    <%= f.input :price, label: "Preço" %>
    <%= f.input :photo, as: :file, input_html: { multiple: true } %>

    <%= f.submit 'Novo Instrumento', class: 'btn-show' %>
  <% end %>

  <hr>

  <%= link_to '<- Voltar a todos instrumentos', instruments_path %>

</div>

app/views/instruments/show.html.erb
<div class="card-show">
  <% if @instrument.photo.any? %>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @instrument.photo.each do |photo| %>
          <div class="carousel-item active">
            <%= cl_image_tag photo.key, class: 'image-cover' %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="card-default">
      <img src="https://i.picsum.photos/id/145/4288/2848.jpg" alt="">
    </div>
  <% end %>

  <div class="card-show-infos">
    <div>
      <h2> <%= @instrument.name.upcase %> </h2>
      <p> <%= @instrument.description %> </p>
    </div>
    <%= link_to orders_path(instrument_id: @instrument.id), method: :post do %>
      <div class="btn-show">
        <span><%= number_to_currency @instrument.price %></span>
      </div>
    <% end %>
    <img src="https://res.cloudinary.com/dy3bkpda4/image/upload/v1583253839/A8B9548F-FC2B-4205-AA06-3E74CE547CBC_4_5005_c_v7mhky.jpg" class="card-show-user avatar-bordered" />

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Toca Aqui</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


    <% unless current_page?(root_path) %>
      <div class="container">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

    <div class="footer">
      <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>

    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@oder) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
  <h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/pages/home.html.erb
  <div class="banner" style="background-image: url('https://res.cloudinary.com/dy3bkpda4/image/upload/v1583262753/grand-piano_v3ttlv.jpg')">
    <div class="container">
      <h1>Toca Aqui traz a você os <br>
      <strong>melhores instrumentos</strong> do mercado!</h1>
      <%= link_to 'Comprar', instruments_path, class: "btn" %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible mx-3" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible mx-3" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm justify-content-between navbar-light navbar-lewagon shadow-sm bg-white rounded navbar transparent navbar-inverse">
  <%= link_to "/", class: "navbar-brand" do %>
  <!-- link_to will redirect to root. -->
      <%= image_tag "toca_aqui-logo.png", alt: "Toca Aqui logo" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "ANÚNCIOS", "/instruments", class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "placeholder_avatar.png", class: "avatar dropdown-toggle", style: 'height: 40px; width: 40px;', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class='mx-3'>Logado como: <b><%= current_user.email %></b></p>
            <% if current_user.admin %>
              <p class='mx-3'><strong>CONTA ADMIN</strong></p>
            <% end %>
            <hr class='mx-2'>
            <% unless current_user.admin %>
              <%= link_to "Meu Perfil", "/profile", class: "dropdown-item" %>
            <% end %>
            <%= link_to "Sair da conta", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <ul class="navbar-nav mr-auto">
        </ul>
        <li class="nav-item">
          <%= link_to "ENTRAR", new_user_session_path, class: "btn btn-warning" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1>Meu perfil</h1>

<h4><%= current_user.email %></h4>